name = "EnzymaticOcean"
uuid = "7da242da-08ed-463a-9acd-ee780be4f1d9"
authors = ["Valentin Churavy <vchuravy@mit.edu>", "Ludger PÃ¤hler <ludger.paehler@tum.de>", "Greg Wagner <glwagner@mit.edu>", "William Moses <wmoses@mit.edu>"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
KernelGradients = "e5faadeb-7f6c-408e-9747-a7a26e81c66a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
